# Generated by Django 3.0.1 on 2020-02-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='numero',
            field=models.IntegerField(default=1, verbose_name='Numero del paso'),
            preserve_default=False,
        ),
    ]
