# Generated by Django 3.0.1 on 2020-06-10 09:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_capitulo_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulo',
            options={'ordering': ['numero'], 'verbose_name': 'Paso', 'verbose_name_plural': 'Pasos'},
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='transcripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Transcripción'),
        ),
    ]
