# Generated by Django 3.0.1 on 2020-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lab', models.CharField(max_length=200, verbose_name='Nombre del evento')),
                ('imagen_lab', models.ImageField(upload_to='cursos/imagenes/', verbose_name='Imagen del evento')),
                ('resumen', models.CharField(max_length=200, verbose_name='Resumen')),
                ('horario', models.CharField(max_length=200, verbose_name='Horario del evento')),
                ('requisitos', models.CharField(max_length=200, verbose_name='Requisitos')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('link_video', models.URLField(verbose_name='Link de la sesion')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_entrada', models.DateTimeField(auto_now=True, verbose_name='Añadido el')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_entrada'],
            },
        ),
    ]
