# Generated by Django 3.0.1 on 2020-08-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='link_video',
            field=models.URLField(blank=True, verbose_name='Link de la sesion'),
        ),
    ]
