# Generated by Django 3.0.1 on 2020-02-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tutorial')),
                ('imagen', models.ImageField(upload_to='tutoriales/imagenes/', verbose_name='Imagen')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('video', models.URLField(verbose_name='Video')),
                ('transcripcion', models.TextField(verbose_name='Transcripción')),
                ('archivoPdf', models.FileField(upload_to='tutoriales/pdfs/')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutoriales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
