# Generated by Django 3.0.1 on 2020-05-04 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriales', '0002_auto_20200505_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='updated',
        ),
    ]
