# Generated by Django 3.0.1 on 2020-06-10 09:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriales', '0003_auto_20200505_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='transcripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Transcripción'),
        ),
    ]
