# Generated by Django 3.0.1 on 2020-05-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=200, verbose_name='Nombre del curso')),
                ('imagen_curso', models.ImageField(upload_to='cursos/imagenes/', verbose_name='Imagen del curso')),
                ('horario', models.CharField(max_length=200, verbose_name='Horario del curso')),
                ('precio', models.CharField(max_length=50, verbose_name='Precio del curso')),
                ('requisitos', models.CharField(max_length=200, verbose_name='Requisitos')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(auto_now=True, verbose_name='Fecha de inicio')),
                ('fecha_entrada', models.DateTimeField(auto_now=True, verbose_name='Añadido el')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-fecha_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=200, verbose_name='Nombre del Alumno')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('edad', models.IntegerField(verbose_name='Edad (mayor de 18)')),
                ('telefono', models.CharField(max_length=20, verbose_name='Número de teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Dirección de email')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia (España)')),
                ('fecha_inscripcion', models.DateTimeField(auto_now=True, verbose_name='Fecha de inscripción')),
                ('contactado', models.BooleanField(default=False)),
                ('comenzado_curso', models.BooleanField(default=False)),
                ('segunda_sesion_prueba', models.BooleanField(default=False)),
                ('pago_realizado', models.BooleanField(default=False)),
                ('finalizado_curso', models.BooleanField(default=False)),
                ('curso_registrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
    ]
