# Generated by Django 3.0.1 on 2020-05-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
