# Generated by Django 3.0.1 on 2020-05-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20200503_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='link_canal',
            field=models.URLField(default=1, verbose_name='Enlace al curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='resumen',
            field=models.CharField(default=1, max_length=200, verbose_name='Resumen'),
            preserve_default=False,
        ),
    ]
