# Generated by Django 3.0.1 on 2020-01-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
