# Generated by Django 3.0.1 on 2020-01-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200108_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
