# Generated by Django 3.0.1 on 2020-05-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200108_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha del comentario')),
                ('aprovado', models.BooleanField(default=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Entrada', verbose_name='Entrada')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha'],
            },
        ),
    ]
