# Generated by Django 3.0.1 on 2020-05-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_entrada_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='slug',
        ),
    ]
