# Generated by Django 3.0.1 on 2020-05-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_entrada_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entrada',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
