# Generated by Django 3.0.1 on 2020-05-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200505_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='titulo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
    ]
