# Generated by Django 3.0.1 on 2020-05-04 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200505_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='updated',
        ),
    ]
