# Generated by Django 3.0.1 on 2020-06-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200610_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='contenido',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
